# HEADER
PARAM_FILE_NAME="Default COV configuration"
PARAM_FILE_AUTHOR="S. Shepard"
PARAM_FILE_VERSION="1.0"
PARAM_FILE_DATE="2020-02"

DEL_T=0.75

DEL_TYPE="REF NNN"
ASSEM_REF=1
ALIGN_PROG="BLAT"
ASSEM_PROG="SSW"
MAX_ROUNDS=5
