# HEADER
PARAM_FILE_NAME="Default COV configuration"
PARAM_FILE_AUTHOR="S. Shepard"
PARAM_FILE_VERSION="1.1"
PARAM_FILE_DATE="2021-02"

# Matches init.sh currently
MAX_ROUNDS=5
ALIGN_PROG="BLAT"
ASSEM_PROG="SSW"

MIN_CONS_SUPPORT=15
MIN_RP=1
MIN_RC=5
