name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'
      - test

permissions: {}

env:
  RELEASE_PKG: irma
  RELEASE_BASE: flu-amd
  REGISTRY: ghcr.io

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6

      - name: Extract Changelog
        id: extract_changelog
        shell: bash
        run: perl .github/scripts/last_release_notes.pl > "$RUNNER_TEMP/release_notes.md"

      - name: Create Source Code Archive
        id: create_archive
        shell: bash
        run: |
          ARCHIVE_NAME="$RUNNER_TEMP/${{ env.RELEASE_PKG }}-${{ github.ref_name }}-universal.zip"
          base="${{ env.RELEASE_BASE }}"
          pkg="${{ env.RELEASE_PKG }}"

          ./.package-label.sh \
          && ./.package-core.sh \
          && cd .. \
          && mv "$pkg" "$base" \
          && zip -r "${ARCHIVE_NAME}" "./$base" -x "$base/.*" -x "$base/Dockerfile*" \
          && echo "archive_name=${ARCHIVE_NAME}" >> "$GITHUB_OUTPUT" \
          && mv "$base" "$pkg"

      - name: Create Release
        id: create_release
        shell: bash
        run: |
          test_opts=()
          [[ "${{ github.ref_name }}" == "test" ]] && test_opts=(--latest=false --draft)

          gh release create "${{ github.ref_name }}" "${{ steps.create_archive.outputs.archive_name }}" \
            --title "IRMA ${{ github.ref_name }}" \
            --notes-file "$RUNNER_TEMP/release_notes.md" \
            "${test_opts[@]}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-release-images:
    name: Build and Push Release Image
    strategy:
      matrix:
        include:
          - arch: amd64
            runner: ubuntu-latest
          - arch: arm64
            runner: ubuntu-24.04-arm
    runs-on: ${{ matrix.runner }}
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v6

      - name: Log in to dhi.io
        uses: docker/login-action@v4
        with:
          registry: dhi.io
          username: ${{ secrets.DHI_REGISTRY_USER }}
          password: ${{ secrets.DHI_REGISTRY_TOKEN }}

      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}
          tags: |
            type=raw,value=${{ github.ref_name }}-${{ matrix.arch }}

      - name: Build and push Docker image
        id: buildpush
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}

  create-image-release-manifest:
    name: Create Release Manifest
    needs: build-release-images
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Log in to the Container registry
        uses: docker/login-action@v4
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push manifests
        shell: bash
        run: |
          REPO=$(echo "${{ env.REGISTRY }}/${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          VERSION="${REPO}:${{ github.ref_name }}"
          LATEST="${REPO}:latest"

          docker buildx imagetools create --tag "$VERSION" \
            "${VERSION}-amd64" "${VERSION}-arm64"

          if [[ "${{ github.ref_name }}" != "test" ]]; then
            docker buildx imagetools create --tag "$LATEST" "$VERSION"
          fi

      - name: Login to DockerHub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to DockerHub
        shell: bash
        run: |
          GHCR_REPO=$(echo "${{ env.REGISTRY }}/${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          DOCKERHUB_REPO=cdcgov/$(echo "${{ github.repository }}" | cut -d'/' -f2 | tr '[:upper:]' '[:lower:]')
          VERSION_TAG="${{ github.ref_name }}"

          [[ "${{ github.ref_name }}" == "test" ]] && DOCKERHUB_REPO+="-dev"

          echo "Copying ${GHCR_REPO}:${VERSION_TAG} to ${DOCKERHUB_REPO}:${VERSION_TAG}"
          docker buildx imagetools create "${GHCR_REPO}:${VERSION_TAG}" --tag "${DOCKERHUB_REPO}:${VERSION_TAG}"

          if [[ "${{ github.ref_name }}" != "test" ]]; then
            echo "Copying ${GHCR_REPO}:latest to ${DOCKERHUB_REPO}:latest"
            docker buildx imagetools create "${GHCR_REPO}:latest" --tag "${DOCKERHUB_REPO}:latest"
          fi
